CREATE TABLE `submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`accountantName` varchar(255) NOT NULL,
	`accountantEmail` varchar(320) NOT NULL,
	`accountantPhone` varchar(50) NOT NULL,
	`clientEmail` varchar(320) NOT NULL,
	`clientPhone` varchar(50) NOT NULL,
	`propertyType` varchar(50) NOT NULL,
	`currentPayment` varchar(50),
	`currentRate` varchar(50),
	`remainingBalance` varchar(50),
	`yearsRemaining` varchar(50),
	`hasHelocOrLiens` varchar(10) NOT NULL,
	`creditCardPayments` varchar(50),
	`autoLoans` varchar(50),
	`personalLoans` varchar(50),
	`studentLoans` varchar(50),
	`otherDebts` varchar(50),
	`totalMonthlyDebt` varchar(50),
	`goalLowerPayment` boolean DEFAULT false,
	`goalPayOffDebt` boolean DEFAULT false,
	`goalAccessEquity` boolean DEFAULT false,
	`goalShortenTerm` boolean DEFAULT false,
	`goalOther` boolean DEFAULT false,
	`goalOtherText` text,
	`mortgageStatementUrl` text,
	`mortgageStatementFilename` varchar(255),
	`emailSent` boolean DEFAULT false,
	`emailSentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `submissions_id` PRIMARY KEY(`id`)
);
